# Generated by Django 2.0.3 on 2018-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
