# Generated by Django 2.0.3 on 2018-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0002_metacommune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subareas', models.IntegerField()),
                ('people', models.IntegerField()),
                ('cards', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('invalid', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('grabowski', models.IntegerField()),
                ('ikonowicz', models.IntegerField()),
                ('kalinowski', models.IntegerField()),
                ('korwin', models.IntegerField()),
                ('krzaklewski', models.IntegerField()),
                ('kwasniewski', models.IntegerField()),
                ('lepper', models.IntegerField()),
                ('lopuszanski', models.IntegerField()),
                ('olechowski', models.IntegerField()),
                ('pawlowski', models.IntegerField()),
                ('walesa', models.IntegerField()),
                ('wilecki', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'contries',
            },
        ),
    ]
