# Generated by Django 2.0.3 on 2018-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0004_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
